import React from "react";
import ReactDOM from "react-dom";
import { Provider } from "react-redux";
import { createStore } from "redux";
import reducer from "./reducers";
import App from "./App";

const initialState = {
  user: {},
  cart: [],
  recipes: [
    {
      id: 1,
      category: "_id",
      name: "Peanut butter and jelly puffs",
      description: "Delicius receipe for your family ",
      popular: false,
      photos: [
        "https://res.cloudinary.com/djcsouoma/image/upload/v1600200830/receipes/rec-1/glliD45sT2YTxTYtGrHX_0S9A0257_ljywnk.jpg",
      ],
      direction: [
        "1. Preheat oven to 375°F.",
        "2. Roll out pizza dough on a lightly floured surface to 1/8 -inch thickness. Using a round cookie cutter or glass 3-inches in diameter, cut circles of dough (re-roll leftover dough).",
        "3. Place 1/2 teaspoon each of peanut butter and jelly in the center of each circle – do not spread. Wrap dough around filling and pinch shut. Place seam side down on a greased cookie sheet. Brush tops lightly with water or an egg wash, (1 egg beaten with 1 tablespoon water). If desired, sprinkle cinnamon and sugar on top before baking.",
        "4. Bake for 15 to 17 minutes until lightly browned. Serve warm. Let cool at least 10 minutes before serving; jelly gets extremely hot. To reheat, place in microwave oven on medium heat, about 5 seconds per puff.",
      ],
      ingredients: [
        "1. (10 ounce) can refrigerated pizza dough",
        "1/4. cup peanut butter",
        "1/4. cup jelly",
      ],
      price: 500,
      comments: [{ id: "text" }],
      qualification: [{ id: "number" }],
    },
    {
      id: 2,
      category: "_id",
      name: "Sheet pan breakfast bake",
      description: "Delicius receipe for your family ",
      popular: false,
      photos: [
        "https://res.cloudinary.com/djcsouoma/image/upload/v1600287758/receipes/rec-2/rec-2-2_pe4075.jpg",
      ],
      direction: [
        "1. Preheat oven to 400 degrees F. Line a baking sheet with parchment paper. Place bacon in a single layer on baking sheet and bake, turning once, until lightly crisp, about 10 minutes. Remove bacon to a towel lined plate; set aside",
        "2. Place potatoes, Italian seasoning, granulated garlic, salt and chili flakes on baking sheet and use tongs or a spoon to combine, then spread into an even layer. Bake until potatoes are starting to turn golden, about 20-30 minutes.",
        "3. Remove baking sheet from oven and sprinkle mozzarella and cheddar cheese over the top. Use a spoon to create 8 wells. Break the eggs into the wells and season with salt and pepper. Place the bacon slices over the potatoes and bake until eggs are set and bacon is completely crisp, about 10-15 minutes more.",
        "4. Garnish with chopped chives or sliced scallions to serve.",
      ],
      ingredients: [
        "8. slices bacon, cut in half",
        "30. ounces frozen and thawed shredded hash brown potatoes",
        "1. tablespoon italian seasoning",
        "1/2. teaspoon granulated garlic",
        "2. teaspoons kosher salt",
        "1. pinch red chili pepper flakes",
        "1 1/2. cups shredded mozzarella cheese",
        "1. cup shredded sharp cheddar cheese",
        "8. large eggs",
        "3. tablespoons chopped chives (garnish) or 3 tablespoons sliced scallions (garnish)",
      ],
      price: 100,
      comments: [{ id: "text" }],
      qualification: [{ id: "number" }],
    },
    {
      id: 3,
      category: "_id",
      name: "Pizza Scrolls",
      description: "Delicius receipe for your family ",
      popular: false,
      photos: [
        "https://res.cloudinary.com/djcsouoma/image/upload/v1600290186/receipes/rec-3/rec3-1_x3o20r.jpg",
      ],
      direction: [
        "1. Preheat oven to 200c.",
        "2. Combine the chopped capsicum, ham and cheese in bowl.",
        "3. Spread the sauce onto each sheet of pastry, leaving a 2cm border along one side, and sprinkle the capsicum mixture over the top.",
        "4. Roll up the pastry to enclose the filling (like a swiss roll), leaving the plain edge until last",
        "5. Brush the edge lightly with water and fold to seal.",
        "6. Cut each roll into 1cm rounds (use serrated bread knife) and place on lined oven trays.",
        "7. Bake for 20 min or until golden.",
      ],
      ingredients: [
        "1/2. small red capsicum, chopped finely",
        "100. g ham or 100 g salami, chopped fine",
        "1/2. cup cheese, grated",
        "1/4. cup pizza sauce",
        "2. sheets ready rolled puff pastry",
      ],
      price: 400,
      comments: [{ id: "text" }],
      qualification: [{ id: "number" }],
    },
    {
      id: 4,
      category: "_id",
      name: "Kittencals's moist cheddar",
      description: "Delicius receipe for your family ",
      popular: false,
      photos: [
        "https://res.cloudinary.com/djcsouoma/image/upload/v1600290838/receipes/rec-4/rec4-1_qapong.jpg",
      ],
      direction: [
        "1. Preheat oven to 350°F.",
        "2. Butter an 11 x 7-inch pan (if using more than 4 breasts use a larger pan).",
        "3. In a bowl, combine melted butter with fresh minced garlic, 1 teaspoon garlic powder and salt.",
        "4. In another bowl, combine the dry breadcrumbs with 1/2 cup finely grated cheddar cheese, Parmesan cheese 1 teaspoon garlic powder and coarse ground black pepper",
        "5. Dip chicken in butter mixture; then in crumb mixture.",
        "6. Place in prepared pan and bake uncovered for 35-45 minutes or until cooked through, larger breasts may take more time (placing the chicken on a rack in a pan will produce an extra crispy crust).",
        "7. Top with shredded cheddar or mozzarella the last 5 minutes of cooking (this is only optional.",
      ],
      ingredients: [
        "1/3. cup butter, melted",
        "2. tablespoons minced garlic (can use more or less)",
        "2. teaspoons garlic powder, divided (garlic lovers can use more)",
        "1/2. teaspoon seasoning salt (or can use white salt)",
        "3/4. cup seasoned dry bread crumb (seasoned or plain)",
        "1/2. cup finely grated cheddar cheese",
        "1/4. cup freshly grated parmesan cheese",
        "1/2. teaspoon ground black pepper (or to taste)",
        "4. boneless skinless chicken breasts",
        "shredded cheddar cheese (optional and use any amount desired, or can use shredded mozzarella cheese)",
      ],
      price: 250,
      comments: [{ id: "text" }],
      qualification: [{ id: "number" }],
    },
    {
      id: 5,
      category: "_id",
      name: "Classic Potato Salad",
      description: "Delicius receipe for your family ",
      popular: false,
      photos: [
        "https://res.cloudinary.com/djcsouoma/image/upload/v1600291293/receipes/rec-5/rec5-1_n9mtw6.jpg",
      ],
      direction: [
        "1. Boil peeled potatoes in salted water until done. Cool to room temperature.",
        "2. Place diced potatoes in large bowl.",
        "3. Mix mayonnaise, cider vinegar, sugar, mustard, salt, garlic powder, and pepper in another bowl.",
        "4. Add to potatoes.",
        "5. Add celery and onions and mix well.",
        "6. Stir in eggs.",
        "7. Sprinkle a little paprika on top.",
      ],
      ingredients: [
        "8. medium potatoes, cooked and diced",
        "1 1/2. cups mayonnaise",
        "2. tablespoons cider vinegar",
        "2. tablespoons sugar",
        "1. tablespoon yellow mustard",
        "1. teaspoon salt",
        "1. teaspoon garlic powder",
        "1/2. teaspoon pepper",
        "2. celery ribs, sliced",
        "1. cup onion, minced",
        "5 hard-boiled eggs",
        "paprika",
      ],
      price: 210,
      comments: [{ id: "text" }],
      qualification: [{ id: "number" }],
    },
    {
      id: 6,
      category: "_id",
      name: "Perfect Pork Tenderloin",
      description: "Delicius receipe for your family ",
      popular: false,
      photos: [
        "https://res.cloudinary.com/djcsouoma/image/upload/v1600292591/receipes/rec-6/rec-6-1_j0vmta.jpg",
      ],
      direction: [
        "1. Determine the EXACT weight of roast from the meat wrapper. Weight will determine how long to cook the roast.",
        "2. Preheat oven to 500 degrees. Remove tenderloin from refrigerator.  Season meat as desired.  Place seasoned meat in an uncovered roasting pan on a shelf in the bottom 1/3 of your oven.",
        "3. Bake EXACTLY 5 1/2 minutes PER POUND. Adjust +/- according to your oven's accuracy and heat retention.",
      ],
      ingredients: [
        "1. lb boneless pork tenderloin",
        "salt and pepper",
        "dry seasoning, of your choice (thyme, savory, rosemary, garlic powder, onion powder, Italian seasoning, or a mixture)",
      ],
      price: 510,
      comments: [{ id: "text" }],
      qualification: [{ id: "number" }],
    },
    {
      id: 7,
      category: "_id",
      name: "waffle Cone Fried Chicken",
      description: "Delicius receipe for your family ",
      popular: false,
      photos: [
        "https://res.cloudinary.com/djcsouoma/image/upload/v1600399097/receipes/rec-7/rec7-1_nqh6ya.jpg",
      ],
      direction: [
        "1. Preheat oil in a heavy bottomed pot to 350 degrees.",
        "2. Combine the chicken and milk in bowl. In another bowl whisk together the flour, salt and pepper. Coat the chicken in the flour mixture.",
        "3. Working in batches fry the chicken until golden brown and fully cooked through, about 4-5 minutes.",
        "4. Remove to a paper towel lined plate and season with salt.",
        "5. To assemble cones, fill waffle cones with chicken, drizzle with cheese sauce and garnish with chives.",
        "6. Cheese sauce: Bring the half and half to a simmer in a saucepan over medium heat. Add the cheese in batches and whisk until smooth. Serve immediately.",
      ],
      ingredients: [
        "2. lbs chicken breasts, boneless skinless cut into 1 inch pieces",
        "1. cup milk",
        "1 1/2. cups flour",
        "1. teaspoon kosher salt",
        "1. teaspoon black pepper",
        "1. cup canola oil (for frying)",
        "1. bunch chives, thinly sliced",
        "6. waffle cones, store bought",
        "1/2. cup half-and-half",
        "2. cups shredded yellow cheddar cheese",
      ],
      price: 110,
      comments: [{ id: "text" }],
      qualification: [{ id: "number" }],
    },
    {
      id: 8,
      category: "_id",
      name: "Hamburgers",
      description: "Delicius receipe for your family ",
      popular: false,
      photos: [
        "https://res.cloudinary.com/djcsouoma/image/upload/v1600399482/receipes/rec-8/rec8-2_g9moya.jpg",
      ],
      direction: [
        "1. Chop garlic cloves on wooden surface then put in mortar and pestle.",
        "2. Add salt and olive oil and make a paste.",
        "3. Add this to the meat along with the Worcestershire and horseradish.",
        "4. Mix everything and adjust ingredients to suit your taste.",
        "5. When you make the patties place an indention in the middle of each one with your thumb (almost all the way through). This keeps the burgers from shrinking. We like ours thick and I like them to stay that way!",
        "6. Salt and Pepper according to taste when done.",
        "7. An added note on 04-03-06 - Thank you all for your positive feedback. It's nice to get confirmation on something I thought was good and different.",
        "8. Please note that I usually add more ingredients than what is called for above. I nuke a tiny hamburger (meatball size) and taste. I usually add more of everything. The horseradish does not taste like horseradish when cooked. It gives it a flavor note that otherwise wouldn't be there. Unless you are allergic to it, please try it.",
      ],
      ingredients: [
        "1. lb good quality lean ground beef",
        "1. tablespoon olive oil",
        "2. garlic cloves",
        "1/4. teaspoon salt",
        "3. tablespoons Worcestershire sauce",
        "1. tablespoon horseradish (optional but good) (optional)",
      ],
      price: 80,
      comments: [{ id: "text" }],
      qualification: [{ id: "number" }],
    },
    {
      id: 9,
      category: "_id",
      name: "Yogurth Fruit Bars",
      description: "Delicius receipe for your family ",
      popular: false,
      photos: [
        "https://res.cloudinary.com/djcsouoma/image/upload/v1600399878/receipes/rec-9/rec9-1_i1pl61.jpg",
      ],
      direction: [
        "1. Preheat oven to 350°F.",
        "2. In a large bowl, mix all dry ingredients. Add dried fruits and walnuts.",
        "3. In a medium bowl, combine yogurt, egg, apple juice concentrate, and oil.",
        "4. Make a well in the center of the dry ingredients and add the wet ingredients until blended.",
        "5. Coat a 9 X 13 inch pan with vegetable spray, spread batter in pan.",
        "6. Bake 45-50 minutes or until done. Cool 10 minutes before slicing.",
        "7. Slice into 8 servings. Freeze in individual portions if desired.",
      ],
      ingredients: [
        "1 1/2. cups whole wheat flour",
        "1. teaspoon baking soda",
        "1/2. teaspoon baking powder",
        "1. teaspoon cinnamon",
        "1/2. teaspoon ground ginger",
        "1. (6 ounce) package mixed dried fruit, coarsely chopped",
        "1/3. cup chopped walnuts (optional)",
        "1. cup plain fat-free yogurt or 1 cup low-fat plain yogurt",
        "1. large egg",
        "1/4. cup apple juice concentrate",
        "2. tablespoons oil",
        "nonstick cooking spray",
      ],
      price: 250,
      comments: [{ id: "text" }],
      "qualificat ion": [{ id: "number" }],
    },
    {
      id: 10,
      category: "_id",
      name: "Cheesy Taco Pockets",
      description: "Delicius receipe for your family ",
      popular: false,
      photos: [
        "https://res.cloudinary.com/djcsouoma/image/upload/v1600400419/receipes/rec-10/rec10-2_qm9csh.jpg",
      ],
      direction: [
        "1. Remove pastry from freezer and allow to thaw at room temperature for about 30- 40 minutes or until they are easy to handle.",
        "2. Meanwhile, add the beef, onion and green pepper to a large skillet and cook until beef is browned and vegetables begin to soften. Stir occasionally to break meat up and prevent scorching.",
        "3. Add garlic and cook for one more minute, stirring constantly.",
        "4. Drain all the grease from the pan and return to the heat.",
        "5. Add tomato, catsup, cilantro or parsley, cumin, chili powder, oregano and cinnamon. Reduce heat to low and allow to simmer for about 10 minutes. You want a pretty dry mixture so your filling stays put in the pastry.",
      ],
      ingredients: [
        "2. (17 1/3 ounce) packages puff pastry sheets, 2 sheets per package",
        "1. egg",
        "1/2. tablespoon water",
        "1 1/2. lbs ground beef",
        "1/2. cup green pepper, chopped",
        "1/2. cup white onion, chopped",
        "1. garlic clove, minced",
        "1. medium tomatoes, seeded and chopped",
        "1/2. cup catsup",
        "1/4. cup fresh cilantro or 1/4 cup parsley, chopped",
        "1. teaspoon ground cumin",
        "2. teaspoons chili powder",
      ],
      price: 310,
      comments: [{ id: "text" }],
      qualification: [{ id: "number" }],
    },
  ],
};

const store = createStore(reducer, initialState);

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.querySelector("#root")
);
